version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: weather_station_app
    ports:
      - "18080:18080"
    volumes:
      - .:/app
      - ./src:/app/src
      - ./include:/app/include
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: bash -c "
      if [ ! -d external/Crow ]; then
      mkdir -p external && git clone --depth=1 https://github.com/CrowCpp/Crow.git external/Crow;
      fi &&
      rm -rf build_app &&
      cmake -S . -B build_app &&
      cmake --build build_app --target Weather_Station_Dashboard &&
      ./build_app/Weather_Station_Dashboard
      "
    deploy:
      restart_policy:
        condition: any
    networks:
      - weather_station_network

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: tests
    container_name: weather_station_tests
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=1883
    command: > 
      bash -ce "
        if [ ! -d external/Crow ]; then
          mkdir -p external && git clone --depth=1 https://github.com/CrowCpp/Crow.git external/Crow;
        fi && 
        rm -rf build && 
        cmake -S . -B build -DBUILD_TESTS=ON &&
        cmake --build build --target runTests -- -j$(nproc) &&
        ./build/runTests --gtest_color=yes --gtest_brief=0
      "
    volumes:
      - .:/app
      - ./src:/app/src
      - ./include:/app/include
      - ./tests:/app/tests
    networks:
      - weather_station_network

    stdin_open: true
    tty: true

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - weather_station_network
    restart: unless-stopped

networks:
  weather_station_network:
    driver: bridge




