version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: weather_station_app
    ports:
      - "18080:18080"
    volumes:
      - ./src:/app/src
      - ./src/templates:/app/templates
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: bash

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: tests
    container_name: weather_station_tests
    command: ["/bin/bash", "-c", "cmake -S . -B build && cmake --build build --target runTests && ./build/runTests --gtest_color=yes"]
    volumes:
      - .:/app
      - ./build:/app/build
    stdin_open: true
    tty: true

