version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: weather_station_app
    ports:
      - "18080:18080"
    volumes:
      - ./src:/app/src
      - ./src/templates:/app/templates
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: bash

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: tests
    container_name: weather_station_tests
    command: > 
      bash -c "
        if [ ! -d external/Crow ]; then
          mkdir -p external && git clone --depth=1 https://github.com/CrowCpp/Crow.git external/Crow;
        fi && 
        rm -rf build && 
        cmake -S . -B build -DBUILD_TESTS=ON &&
        cmake --build build --target runTests -- -j$(nproc) &&
        ./build/runTests --gtest_color=yes 
      "
    volumes:
      - .:/app
    stdin_open: true
    tty: true

